// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateRequest(arg1) {
  return window['go']['main']['App']['CreateRequest'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function LoadWorkspace() {
  return window['go']['main']['App']['LoadWorkspace']();
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function UpdateCollection(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2);
}

export function UpdateFolder(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2);
}

export function UpdateRequest(arg1) {
  return window['go']['main']['App']['UpdateRequest'](arg1);
}
