// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCollection(arg1:string):Promise<main.Collection>;
export function CreateFolder(arg1:string,arg2:string):Promise<main.Folder>;
export function CreateRequest(arg1:main.CreateRequestInput):Promise<main.SavedRequest>;
export function DeleteCollection(arg1:string):Promise<void>;
export function DeleteFolder(arg1:string):Promise<void>;
export function DeleteRequest(arg1:string):Promise<void>;
export function LoadWorkspace():Promise<main.Workspace>;
export function SaveWorkspace(arg1:main.Workspace):Promise<void>;
export function SendRequest(arg1:main.APIRequest):Promise<main.APIResponse>;
export function UpdateCollection(arg1:string,arg2:string):Promise<main.Collection>;
export function UpdateFolder(arg1:string,arg2:string):Promise<main.Folder>;
export function UpdateRequest(arg1:main.UpdateRequestInput):Promise<main.SavedRequest>;
