// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadWorkspace():Promise<main.Workspace>;
export function SaveWorkspace(arg1:main.Workspace):Promise<void>;
export function SendRequest(arg1:main.APIRequest):Promise<main.APIResponse>;
